### ISSUE TITLE
Ember 3.0

### ISSUE THREAD

**Issue by lordblendi** [tenforce/ember-mu-application-generator#10]
- Upgrade to Ember 3.0
- Fix JSHint errors

**Comment by erikap** [comment]
@lordblendi We're working on an upgrade to 3.0 which fixes the JSHint errors. We didn't fix the route menu. Shall we make a PR?

**Comment by lordblendi** [comment]
For me PR is not needed. If you or @nvdk can manage it, that's fine for me. Then I'll make a separate issue for the route menu and start working on that, unless you also plan to do that.

**Comment by madnificent** [comment]
Hi @lordblendi.  We're not working on the menu at the moment.  It would be nice if you could get that running with 3.0.

**Comment by lordblendi** [comment]
Thanks @madnificent and @erikap, I've created an issue for the menu and started working on it: https://github.com/tenforce/ember-mu-application-generator/issues/11

**Comment by langens-jonathan** [comment]
Hey I'm sorry but I'm afraid that a PR is still easier for the company to track. Thanks @erikap and @madnificent though for the fixes :)

**Comment by madnificent** [comment]
Check.  We'll make a PR of the progress we've made once we've ported our changes.  You can add the menu to that, and tag once we hit full 3.0 compatibility.  We'll probably finish within two weeks (and hopefully much earlier).

**Comment by langens-jonathan** [comment]
thank you @madnificent

**Comment by lordblendi** [comment]
Yesterday I tagged a version for Ember 2.14, now I pushed the change for navigation menu with ember 3.0.

**Comment by madnificent** [comment]
Hi @lordblendi.  This is great!  Is it ok for you if I pull in your changes whilst working on our part of the upgrade, see if everything works as expected, and create a pull request with everything included?  The commit-history will be left in-tact either case, but it makes our workflow easier.

**Comment by lordblendi** [comment]
Hey @madnificent. Please do so, it's in the master branch here. And if you see any problems with it, don't hesitate to reopen the other issue.

**Comment by lordblendi** [comment]
Fixed in https://github.com/tenforce/ember-mu-application-generator/pull/12
